---

- hosts: all
  become: true
  tasks:
     
   - name: install the httpd and php packages on CentOS pkg
       yum:
         name:
           - httpd
           - php 
         state: latest
         update_cache: yes
       when: ansible_distribution == "CentOS"

     - name: start httpd web server
       service:
         name: httpd
         state: started  
       when: ansible_distribution == "CentOS"

     - name: install the apache2 package on Ubuntu
       apt:
         name: 
           - apache2
           - libapache2-mod-php 
         state: latest     
         update_cache: yes   
       when: ansible_distribution == "Ubuntu"

    
                
