---

- hosts: all
  become: true
  tasks:
     - name: update repository index
       yum:
         update_cache: yes
       when: ansible_distribution == "CentOS"

    - name: update repository index for Ubuntu
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"


     - name: install the httpd package on CentOS pkg
       yum:
          name: httpd
          state: latest
       when: ansible_distribution == "CentOS"

     - name: start httpd web server
       service:
         name: httpd
         state: started  
       when: ansible_distribution == "CentOS"

     - name: add php support for httpd
       yum:
         name: php
         state: latest
       when: ansible_distribution == "CentOS"

     - name: install the apache2 package on Ubuntu
       apt:
         name: apache2
         state: latest        
       when: ansible_distribution == "Ubuntu"

     - name: add php support for apache2
       apt:
         name: libapache2-mod-php
         state: latest
       when: ansible_distribution == "Ubuntu"     
