---

- hosts: all
  become: true
  pre_tasks:
     
     - name: install updates for CentOS
       tags: always
       yum:
         update_only: yes
         update_cache: yes
       when: ansible_distribution == "CentOS"

     - name: install updates on Ubuntu
       tags: always
       apt:
         upgrade: dist
         update_cache: yes
       when: ansible_distribution == "Ubuntu"
       

- hosts: web_servers
  become: true
  tasks:
     
     - name: install the httpd and php packages on CentOS pkg
       tags: centos,httpd
       yum:
         name:
           - httpd
           - php 
         state: latest
       when: ansible_distribution == "CentOS"

     - name: start httpd web server
       service:
         name: httpd
         state: started  
       when: ansible_distribution == "CentOS"

     - name: install the apache2 package on Ubuntu
       tags: apache2,ubuntu
       apt:
         name: 
           - apache2
           - libapache2-mod-php 
         state: latest     
       when: ansible_distribution == "Ubuntu"
   
     - name: copy default html file for site
       tags: httpd, apache, apache2
       copy:
         src: /home/osboxes/ansible_tutorial/file/default_site.html
         dest: /var/www/html/index.html 
         owner: root
         group: root
         mode: '0644'

- hosts: database_server
  become: true
  tasks:
     - name: install mariadb on CentOS server
       tags: centos, mariadb
       yum:
         name: mariadb
         state: latest	    
       when: ansible_distribution == "CentOS"

     - name: install mariadb package on Ubuntu server
       tags: ubuntu,mariadb-server
       apt:
         name: mariadb-server
         state: latest
       when: ansible_distribution == "Ubuntu"    
                
